### ISSUE TITLE
support for Japanese language and lower case

### ISSUE THREAD

**Issue by Asciicodeplus** [Bearborg/decima-scripts#1]
This script also works for the PS4 version of the files and one hidden language that is not included in the western region of the Steam version:

DLC1_Japanese.bin
Initial_Japanese.bin
Remainder_Japanese.bin

the japanese language is only available in the PS4 version for Japan (CUSA10234) and from Steam when setting your country region to Japan, the japanese section is missing in the language_stream_contents.py and it also doesn't recognize the files if they are written in lower case (i.e.: initial_japanese.bin), can you add support for japanese and lower case (or case insensitive)?

**Comment by Bearborg** [comment]
I don't have access to the Japanese language files, but I've made changes that should allow it to work. Could you test out the new version?

**Comment by Asciicodeplus** [comment]
it works, thx :D

**Comment by Bearborg** [comment]
Glad to hear it!
