### ISSUE TITLE
*.bin

### ISSUE THREAD

**Issue by czdvoika** [Bearborg/decima-scripts#2]
Hi, can you create a *.bin file with multiple files? decima explorer can only handle one file, with multiple files it won't load :(

**Comment by Bearborg** [comment]
Sorry for the very late response- I haven't worked on .bin repacking, so I'm not sure how to get around that issue with Decima Explorer either. You may want to check out [ShadlessFox's Decima Workshop tool](https://github.com/ShadelessFox/decima), which (I think) also supports repacking .bin files.
